//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VastecOPMSP.OPMViewPriorityRequestsWP {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class OPMViewPriorityRequestsWP {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "15.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(OPMViewPriorityRequestsWP target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__BuildControlTree(global::VastecOPMSP.OPMViewPriorityRequestsWP.OPMViewPriorityRequestsWP @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"

<script src=""/_layouts/15/Common/scripts/js/jquery.min.js""></script>
<script src=""/_layouts/15/Common/scripts/js/jquery-ui.min.js""></script>
<script src=""/_layouts/15/Common/scripts/js/bootstrap.min.js""></script>
<script src=""/_layouts/15/Common/scripts/js/underscore.js""></script>
<script src=""/_layouts/15/Common/scripts/js/jquery.validate.min.js""></script>
<script src=""/_layouts/15/Common/scripts/js/jquery.dataTables.min.js""></script>
<script src=""/_layouts/15/Common/scripts/js/jspdf.min.js""></script>
<script src=""/_layouts/15/Common/scripts/js/jspdf.plugin.autotable.min.js""></script>
<script src=""/_layouts/15/Common/scripts/js/jspdf.autotable.standard_fonts_metrics.js"" type=""text/javascript""></script>
<script src=""/_layouts/15/Common/scripts/js/jspdf.autotable.split_text_to_size.js"" type=""text/javascript""></script>
<link href=""/_layouts/15/Common/styles/css/bootstrap.min.css"" rel=""stylesheet"" type=""text/css"" />
<link href=""/_layouts/15/Common/styles/css/jquery-ui.css"" rel=""stylesheet"" type=""text/css"" />
<link href=""/_layouts/15/Common/styles/css/jquery.dataTables.min.css"" rel=""stylesheet"" type=""text/css"" />

<script src=""/_layouts/15/VastecOPMSP/ViewPriorityRequests.js?ver=");
                                                          @__w.Write(DateTime.Now.Ticks.ToString());

            @__w.Write("\" type=\"text/javascript\"></script>\r\n<script src=\"/_layouts/15/VastecOPMSP/Common." +
                    "js?ver=");
                                            @__w.Write(DateTime.Now.Ticks.ToString());

            @__w.Write("\" type=\"text/javascript\"></script>\r\n<link href=\"/_layouts/15/VastecOPMSP/style.cs" +
                    "s?ver=");
                                           @__w.Write(DateTime.Now.Ticks.ToString());

            @__w.Write(@""" rel=""stylesheet"" type=""text/css"" />

<style>
    .popup-table-cell {
        width: 100%;
        padding: 5px;
    }
</style>

<div id=""manifestParentDiv"" style=""display: none"">
    <br />    
    <div class=""global-search-wrapper"">
        Search:
        <input type=""text"" id=""globalSearch"">
        <button type=""button"" class=""btn btn-info"" id=""btnGlobalSearch"">Search</button>
        <button type=""button"" class=""btn btn-info"" id=""btnClearGlobalSearch"">Clear Search</button>
    </div>
    <br />    
     <div class=""row"">
        <div class=""col-md-6"">
            <h3>View Priority Requests</h3>
        </div>
        <div class=""col-md-6 global-search-wrapper help-text"">
            <span tabindex=""0"" class=""wf wf-size-x18 wf-family-o365 wf-o365-question"" role=""presentation"" style=""font-size: 22px; vertical-align: middle; display: inline-block; cursor: pointer;"" id=""helpText"" data-toggle=""popover"" data-trigger=""focus""></span>
        </div>
    </div>
    
    <br />
    <table class=""manifest-elements-table display dataTable cell-border compact globalSearch"" id=""manifestElementsTable""></table>    
</div>");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "15.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
